const EXIT_MAP: Record<string, number> = {
  // CLI_* (config/credentials → 2)
  CLI_CONFIG_MISSING: 2,
  CLI_CONFIG_INVALID: 2,
  CLI_CONFIG_ARTIFACT_NOT_FOUND: 2,
  CLI_CREDENTIALS_MISSING: 2,
  CLI_CREDENTIALS_INVALID: 2,
  CLI_CREDENTIALS_PERMISSIONS_TOO_OPEN: 2,
  CLI_USAGE: 2,
  CLI_INIT_ALREADY_INITIALIZED: 2,
  CLI_INIT_INVALID_SLUG: 2,
  CLI_SKILLS_UNKNOWN_AGENT: 2,
  CLI_SKILLS_TARGET_NOT_WRITABLE: 2,
  CLI_RESPONSE_PARSE_FAILED: 10,
  CLI_VALIDATE_LOCAL_FAILED: 6,
  CLI_PUBLISH_DIGEST_MISMATCH: 1,
  CLI_NETWORK_TIMEOUT: 9,

  // PLATFORM_AUTH_*
  PLATFORM_AUTH_MISSING: 3,
  PLATFORM_AUTH_INVALID: 3,
  PLATFORM_AUTH_TOKEN_REVOKED: 3,
  PLATFORM_AUTH_TOKEN_EXPIRED: 3,
  PLATFORM_AUTH_FORBIDDEN: 4,

  // Parse → 2 (config-like from client perspective)
  PLATFORM_PARSE_BODY_INVALID: 2,
  PLATFORM_PARSE_PATH_INVALID: 2,

  // Tenancy → 5
  PLATFORM_TENANCY_ORG_NOT_FOUND: 5,
  PLATFORM_TENANCY_PROJECT_NOT_FOUND: 5,
  PLATFORM_TENANCY_SERVICE_NOT_FOUND: 5,
  PLATFORM_TENANCY_RESOURCE_ARCHIVED: 5,

  // Validation → 6
  PLATFORM_VALIDATION_BUNDLE_FAILED: 6,

  // Concurrency → 7
  PLATFORM_CONCURRENCY_VERSION_CONFLICT: 7,
  PLATFORM_CONCURRENCY_LAST_OWNER: 7,

  // Rate limit → 8
  PLATFORM_RATE_LIMITED: 8,

  // Storage / internal → 10
  PLATFORM_STORAGE_BLOB_UPLOAD_FAILED: 10,
  PLATFORM_STORAGE_DB_UNAVAILABLE: 10,
  PLATFORM_INTERNAL: 10,
  PLATFORM_WORKOS_WEBHOOK_INVALID: 10,
  PLATFORM_WORKOS_UNAVAILABLE: 10,
};

export function exitCodeFor(code: string | undefined): number {
  if (!code) return 1;
  return EXIT_MAP[code] ?? 1;
}
