export const DEPLOY_CORE_ERROR_CODES = {
  DEPLOY_PLAN_UNSUPPORTED_PRODUCTION_MODE: 'DEPLOY_PLAN_UNSUPPORTED_PRODUCTION_MODE',
  DEPLOY_PLAN_INVALID_ENVIRONMENT: 'DEPLOY_PLAN_INVALID_ENVIRONMENT',
  DEPLOY_PLAN_MISSING_ORG_SLUG: 'DEPLOY_PLAN_MISSING_ORG_SLUG',
  DEPLOY_PLAN_MISSING_EVENT_BUS: 'DEPLOY_PLAN_MISSING_EVENT_BUS',
  DEPLOY_PLAN_MISSING_MODULE_IMAGE: 'DEPLOY_PLAN_MISSING_MODULE_IMAGE',
  DEPLOY_PLAN_PUBLIC_MODULE_NOT_EXPOSED: 'DEPLOY_PLAN_PUBLIC_MODULE_NOT_EXPOSED',
  DEPLOY_PLAN_UNSUPPORTED_MIDDLEWARE: 'DEPLOY_PLAN_UNSUPPORTED_MIDDLEWARE',
  DEPLOY_PLAN_MISSING_POLICY_VALUE: 'DEPLOY_PLAN_MISSING_POLICY_VALUE',
  DEPLOY_PLAN_ROUTE_TARGET_MISSING_WORKLOAD: 'DEPLOY_PLAN_ROUTE_TARGET_MISSING_WORKLOAD',
} as const;

export type DeploymentPlanErrorCode = keyof typeof DEPLOY_CORE_ERROR_CODES;

export type DeploymentPlanError = {
  readonly code: DeploymentPlanErrorCode;
  readonly message: string;
  readonly path?: string;
  readonly service?: string;
  readonly route?: string;
  readonly middleware?: string;
  readonly policy?: string;
};
